# Regenerates src/three/wordmarkGlyphs.ts (needs fontTools + brotli):
#   python3 scripts/makeWordmarkGlyphs.py node_modules/@fontsource-variable/fredoka/files/fredoka-latin-wdth-normal.woff2 \
#     > src/three/wordmarkGlyphs.ts
# Variable fonts are instanced at wght 700 (and wdth 125 when the font has a width
# axis) first; static ones are used as they are.
import json, os, sys
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen

font = TTFont(sys.argv[1])
location = {}
if "fvar" in font:
    axes = {a.axisTag for a in font["fvar"].axes}
    location = {"wght": 700, **({"wdth": 125} if "wdth" in axes else {})}
    font = instantiateVariableFont(font, location)

cmap = font.getBestCmap()
glyphs = font.getGlyphSet()
out = {"unitsPerEm": font["head"].unitsPerEm, "glyphs": {}}
for ch in "alu":
    name = cmap[ord(ch)]
    pen = SVGPathPen(glyphs)
    glyphs[name].draw(pen)
    out["glyphs"][ch] = {"advance": font["hmtx"][name][0], "path": pen.getCommands()}

# name tables aren't updated by the instancer, so describe the instance ourselves
instance = ", ".join(f"{k} {v}" for k, v in location.items()) or "static"
print(f"// Generated by scripts/makeWordmarkGlyphs.py from {os.path.basename(sys.argv[1])} ({instance}, SIL OFL). Do not edit.")
print("// Paths are in font units, y up.")
print("export const WORDMARK_GLYPHS = " + json.dumps(out, indent="\t") + " as const;")
